/**
 * Every machine-readable code the API can return.
 *
 * Mobile clients switch on `code`, never on `message` (which is localisable and
 * may change). Codes are grouped by domain and are stable API surface — treat a
 * rename as a breaking change.
 */
export const ResponseCode = {
  // ── Generic ──
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  FETCHED: 'FETCHED',

  // ── Generic errors ──
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 'IDEMPOTENCY_REQUEST_IN_PROGRESS',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',

  // ── Auth ──
  REGISTERED: 'REGISTERED',
  LOGGED_IN: 'LOGGED_IN',
  LOGGED_OUT: 'LOGGED_OUT',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  PASSWORD_SET: 'PASSWORD_SET',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  OTP_SENT: 'OTP_SENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_RESENT: 'OTP_RESENT',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS_REACHED: 'OTP_MAX_ATTEMPTS_REACHED',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',

  // ── Profile / account ──
  PROFILE_FETCHED: 'PROFILE_FETCHED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  AVATAR_UPDATED: 'AVATAR_UPDATED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_HAS_ACTIVE_DELIVERIES: 'ACCOUNT_HAS_ACTIVE_DELIVERIES',
  ACCOUNT_HAS_WALLET_BALANCE: 'ACCOUNT_HAS_WALLET_BALANCE',

  // ── Address ──
  ADDRESSES_FETCHED: 'ADDRESSES_FETCHED',
  ADDRESS_FETCHED: 'ADDRESS_FETCHED',
  ADDRESS_CREATED: 'ADDRESS_CREATED',
  ADDRESS_UPDATED: 'ADDRESS_UPDATED',
  ADDRESS_DELETED: 'ADDRESS_DELETED',
  ADDRESS_DEFAULT_SET: 'ADDRESS_DEFAULT_SET',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_LIMIT_REACHED: 'ADDRESS_LIMIT_REACHED',

  // ── Location / map ──
  LOCATIONS_FETCHED: 'LOCATIONS_FETCHED',
  LOCATION_FETCHED: 'LOCATION_FETCHED',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  MAP_PROVIDER_UNAVAILABLE: 'MAP_PROVIDER_UNAVAILABLE',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',

  // ── Vehicle types ──
  VEHICLE_TYPES_FETCHED: 'VEHICLE_TYPES_FETCHED',
  VEHICLE_TYPE_NOT_FOUND: 'VEHICLE_TYPE_NOT_FOUND',
  VEHICLE_TYPE_INACTIVE: 'VEHICLE_TYPE_INACTIVE',

  // ── Drivers (customer-facing) ──
  NEARBY_DRIVERS_FETCHED: 'NEARBY_DRIVERS_FETCHED',
  FAVORITE_DRIVERS_FETCHED: 'FAVORITE_DRIVERS_FETCHED',
  FAVORITE_DRIVER_ADDED: 'FAVORITE_DRIVER_ADDED',
  FAVORITE_DRIVER_REMOVED: 'FAVORITE_DRIVER_REMOVED',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  FAVORITE_DRIVER_ALREADY_ADDED: 'FAVORITE_DRIVER_ALREADY_ADDED',

  // ── Package templates ──
  PACKAGE_TEMPLATES_FETCHED: 'PACKAGE_TEMPLATES_FETCHED',
  PACKAGE_TEMPLATE_CREATED: 'PACKAGE_TEMPLATE_CREATED',
  PACKAGE_TEMPLATE_UPDATED: 'PACKAGE_TEMPLATE_UPDATED',
  PACKAGE_TEMPLATE_DELETED: 'PACKAGE_TEMPLATE_DELETED',
  PACKAGE_TEMPLATE_NOT_FOUND: 'PACKAGE_TEMPLATE_NOT_FOUND',

  // ── Delivery ──
  QUOTE_CALCULATED: 'QUOTE_CALCULATED',
  DELIVERY_CREATED: 'DELIVERY_CREATED',
  DELIVERIES_FETCHED: 'DELIVERIES_FETCHED',
  DELIVERY_FETCHED: 'DELIVERY_FETCHED',
  DELIVERY_PACKAGES_FETCHED: 'DELIVERY_PACKAGES_FETCHED',
  DELIVERY_CANCELLED: 'DELIVERY_CANCELLED',
  DELIVERY_REBOOKED: 'DELIVERY_REBOOKED',
  DELIVERY_TRACKING_FETCHED: 'DELIVERY_TRACKING_FETCHED',
  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
  DELIVERY_ALREADY_ASSIGNED: 'DELIVERY_ALREADY_ASSIGNED',
  DELIVERY_NOT_ASSIGNED: 'DELIVERY_NOT_ASSIGNED',
  DELIVERY_INVALID_TRANSITION: 'DELIVERY_INVALID_TRANSITION',
  DELIVERY_NOT_CANCELLABLE: 'DELIVERY_NOT_CANCELLABLE',
  DELIVERY_ALREADY_CANCELLED: 'DELIVERY_ALREADY_CANCELLED',
  DELIVERY_ALREADY_COMPLETED: 'DELIVERY_ALREADY_COMPLETED',
  DELIVERY_EXPIRED: 'DELIVERY_EXPIRED',
  DELIVERY_NO_DRIVER_FOUND: 'DELIVERY_NO_DRIVER_FOUND',
  DELIVERY_DISTANCE_TOO_LONG: 'DELIVERY_DISTANCE_TOO_LONG',
  DELIVERY_SAME_PICKUP_DROPOFF: 'DELIVERY_SAME_PICKUP_DROPOFF',
  PROOF_OF_DELIVERY_REQUIRED: 'PROOF_OF_DELIVERY_REQUIRED',
  PROOF_OF_DELIVERY_SAVED: 'PROOF_OF_DELIVERY_SAVED',

  // ── Promo ──
  PROMO_VALID: 'PROMO_VALID',
  PROMO_NOT_FOUND: 'PROMO_NOT_FOUND',
  PROMO_EXPIRED: 'PROMO_EXPIRED',
  PROMO_NOT_STARTED: 'PROMO_NOT_STARTED',
  PROMO_INACTIVE: 'PROMO_INACTIVE',
  PROMO_USAGE_LIMIT_REACHED: 'PROMO_USAGE_LIMIT_REACHED',
  PROMO_CUSTOMER_LIMIT_REACHED: 'PROMO_CUSTOMER_LIMIT_REACHED',
  PROMO_MIN_ORDER_NOT_MET: 'PROMO_MIN_ORDER_NOT_MET',
  PROMO_VEHICLE_NOT_ELIGIBLE: 'PROMO_VEHICLE_NOT_ELIGIBLE',
  PROMO_CURRENCY_MISMATCH: 'PROMO_CURRENCY_MISMATCH',

  // ── Payment ──
  PAYMENT_METHODS_FETCHED: 'PAYMENT_METHODS_FETCHED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_FETCHED: 'PAYMENT_FETCHED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
  PAYMENT_METHOD_NOT_SUPPORTED: 'PAYMENT_METHOD_NOT_SUPPORTED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',

  // ── Rating ──
  RATING_SUBMITTED: 'RATING_SUBMITTED',
  RATING_FETCHED: 'RATING_FETCHED',
  RATING_ALREADY_SUBMITTED: 'RATING_ALREADY_SUBMITTED',
  RATING_NOT_ALLOWED: 'RATING_NOT_ALLOWED',
  RATING_NOT_FOUND: 'RATING_NOT_FOUND',

  // ── Driver app ──
  DRIVER_PROFILE_FETCHED: 'DRIVER_PROFILE_FETCHED',
  DRIVER_PROFILE_UPDATED: 'DRIVER_PROFILE_UPDATED',
  DRIVER_VEHICLE_FETCHED: 'DRIVER_VEHICLE_FETCHED',
  DRIVER_VEHICLE_UPDATED: 'DRIVER_VEHICLE_UPDATED',
  DRIVER_DOCUMENTS_FETCHED: 'DRIVER_DOCUMENTS_FETCHED',
  DRIVER_DOCUMENT_UPLOADED: 'DRIVER_DOCUMENT_UPLOADED',
  DRIVER_AVAILABILITY_UPDATED: 'DRIVER_AVAILABILITY_UPDATED',
  DRIVER_LOCATION_UPDATED: 'DRIVER_LOCATION_UPDATED',
  DRIVER_DASHBOARD_FETCHED: 'DRIVER_DASHBOARD_FETCHED',
  DRIVER_NOT_APPROVED: 'DRIVER_NOT_APPROVED',
  DRIVER_SUSPENDED: 'DRIVER_SUSPENDED',
  DRIVER_REJECTED: 'DRIVER_REJECTED',
  DRIVER_DOCUMENTS_INCOMPLETE: 'DRIVER_DOCUMENTS_INCOMPLETE',
  DRIVER_VEHICLE_REQUIRED: 'DRIVER_VEHICLE_REQUIRED',
  DRIVER_HAS_ACTIVE_DELIVERY: 'DRIVER_HAS_ACTIVE_DELIVERY',
  DRIVER_NOT_ONLINE: 'DRIVER_NOT_ONLINE',
  DRIVER_VEHICLE_NOT_FOUND: 'DRIVER_VEHICLE_NOT_FOUND',
  DRIVER_DOCUMENT_NOT_FOUND: 'DRIVER_DOCUMENT_NOT_FOUND',

  // ── Driver jobs ──
  JOB_REQUESTS_FETCHED: 'JOB_REQUESTS_FETCHED',
  JOB_FETCHED: 'JOB_FETCHED',
  JOB_ACCEPTED: 'JOB_ACCEPTED',
  JOB_DECLINED: 'JOB_DECLINED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_OFFER_EXPIRED: 'JOB_OFFER_EXPIRED',
  JOB_ALREADY_RESPONDED: 'JOB_ALREADY_RESPONDED',
  JOB_NOT_OFFERED_TO_DRIVER: 'JOB_NOT_OFFERED_TO_DRIVER',
  ARRIVED_PICKUP_CONFIRMED: 'ARRIVED_PICKUP_CONFIRMED',
  PICKUP_CONFIRMED: 'PICKUP_CONFIRMED',
  ARRIVED_DROPOFF_CONFIRMED: 'ARRIVED_DROPOFF_CONFIRMED',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',

  // ── Earnings & wallet ──
  EARNINGS_SUMMARY_FETCHED: 'EARNINGS_SUMMARY_FETCHED',
  EARNINGS_FETCHED: 'EARNINGS_FETCHED',
  EARNING_FETCHED: 'EARNING_FETCHED',
  EARNING_NOT_FOUND: 'EARNING_NOT_FOUND',
  WALLET_FETCHED: 'WALLET_FETCHED',
  WALLET_TRANSACTIONS_FETCHED: 'WALLET_TRANSACTIONS_FETCHED',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // ── Withdrawal ──
  WITHDRAWAL_SETTINGS_FETCHED: 'WITHDRAWAL_SETTINGS_FETCHED',
  WITHDRAWAL_SETTINGS_UPDATED: 'WITHDRAWAL_SETTINGS_UPDATED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWALS_FETCHED: 'WITHDRAWALS_FETCHED',
  WITHDRAWAL_FETCHED: 'WITHDRAWAL_FETCHED',
  WITHDRAWAL_CANCELLED: 'WITHDRAWAL_CANCELLED',
  WITHDRAWAL_NOT_FOUND: 'WITHDRAWAL_NOT_FOUND',
  WITHDRAWAL_SETTINGS_REQUIRED: 'WITHDRAWAL_SETTINGS_REQUIRED',
  WITHDRAWAL_AMOUNT_TOO_LOW: 'WITHDRAWAL_AMOUNT_TOO_LOW',
  WITHDRAWAL_AMOUNT_TOO_HIGH: 'WITHDRAWAL_AMOUNT_TOO_HIGH',
  WITHDRAWAL_PENDING_EXISTS: 'WITHDRAWAL_PENDING_EXISTS',
  WITHDRAWAL_NOT_CANCELLABLE: 'WITHDRAWAL_NOT_CANCELLABLE',

  // ── Chat ──
  CONVERSATIONS_FETCHED: 'CONVERSATIONS_FETCHED',
  MESSAGES_FETCHED: 'MESSAGES_FETCHED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_CLOSED: 'CONVERSATION_CLOSED',

  // ── Notifications ──
  NOTIFICATIONS_FETCHED: 'NOTIFICATIONS_FETCHED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATIONS_READ_ALL: 'NOTIFICATIONS_READ_ALL',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  DEVICE_REGISTERED: 'DEVICE_REGISTERED',
  DEVICE_UNREGISTERED: 'DEVICE_UNREGISTERED',

  // ── Back office ──
  DASHBOARD_FETCHED: 'DASHBOARD_FETCHED',
  ADMIN_DRIVERS_FETCHED: 'ADMIN_DRIVERS_FETCHED',
  ADMIN_DRIVER_FETCHED: 'ADMIN_DRIVER_FETCHED',
  DRIVER_APPROVED: 'DRIVER_APPROVED',
  DRIVER_REJECTED_DECISION: 'DRIVER_REJECTED_DECISION',
  DRIVER_SUSPENDED_DECISION: 'DRIVER_SUSPENDED_DECISION',
  DRIVER_REINSTATED: 'DRIVER_REINSTATED',
  DRIVER_UPDATED: 'DRIVER_UPDATED',
  DRIVER_ALREADY_APPROVED: 'DRIVER_ALREADY_APPROVED',
  DRIVER_NOT_SUSPENDED: 'DRIVER_NOT_SUSPENDED',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_REVIEWED: 'DOCUMENT_REVIEWED',
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  DRIVER_ZONES_UPDATED: 'DRIVER_ZONES_UPDATED',
  EXPORT_TOO_LARGE: 'EXPORT_TOO_LARGE',
  CAMPAIGNS_FETCHED: 'CAMPAIGNS_FETCHED',
  CAMPAIGN_FETCHED: 'CAMPAIGN_FETCHED',
  CAMPAIGN_QUEUED: 'CAMPAIGN_QUEUED',
  CAMPAIGN_CANCELLED: 'CAMPAIGN_CANCELLED',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_NOT_CANCELLABLE: 'CAMPAIGN_NOT_CANCELLABLE',
  AUDIENCE_PREVIEWED: 'AUDIENCE_PREVIEWED',
  ROLES_FETCHED: 'ROLES_FETCHED',
  ROLE_FETCHED: 'ROLE_FETCHED',
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_NAME_TAKEN: 'ROLE_NAME_TAKEN',
  ROLE_IS_SYSTEM: 'ROLE_IS_SYSTEM',
  ROLE_IN_USE: 'ROLE_IN_USE',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  ADMINS_FETCHED: 'ADMINS_FETCHED',
  ADMIN_FETCHED: 'ADMIN_FETCHED',
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_SUSPENDED: 'ADMIN_SUSPENDED',
  ADMIN_REINSTATED: 'ADMIN_REINSTATED',
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  SUPER_ADMIN_REQUIRED: 'SUPER_ADMIN_REQUIRED',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  LAST_SUPER_ADMIN: 'LAST_SUPER_ADMIN',
  AUDIT_LOGS_FETCHED: 'AUDIT_LOGS_FETCHED',
  VEHICLE_TYPES_MANAGED: 'VEHICLE_TYPES_MANAGED',
  VEHICLE_TYPE_CREATED: 'VEHICLE_TYPE_CREATED',
  VEHICLE_TYPE_UPDATED: 'VEHICLE_TYPE_UPDATED',
  VEHICLE_TYPE_CODE_TAKEN: 'VEHICLE_TYPE_CODE_TAKEN',
  ZONES_FETCHED: 'ZONES_FETCHED',
  ZONE_FETCHED: 'ZONE_FETCHED',
  ZONE_CREATED: 'ZONE_CREATED',
  ZONE_UPDATED: 'ZONE_UPDATED',
  ZONE_DELETED: 'ZONE_DELETED',
  ZONE_CODE_TAKEN: 'ZONE_CODE_TAKEN',
  PRICING_RULES_FETCHED: 'PRICING_RULES_FETCHED',
  PRICING_RULE_FETCHED: 'PRICING_RULE_FETCHED',
  PRICING_RULE_CREATED: 'PRICING_RULE_CREATED',
  PRICING_RULE_UPDATED: 'PRICING_RULE_UPDATED',
  PRICING_RULE_DEACTIVATED: 'PRICING_RULE_DEACTIVATED',
  PRICING_RULE_NOT_FOUND: 'PRICING_RULE_NOT_FOUND',
  PROMO_CODES_FETCHED: 'PROMO_CODES_FETCHED',
  PROMO_CODE_FETCHED: 'PROMO_CODE_FETCHED',
  PROMO_CODE_CREATED: 'PROMO_CODE_CREATED',
  PROMO_CODE_UPDATED: 'PROMO_CODE_UPDATED',
  PROMO_CODE_DELETED: 'PROMO_CODE_DELETED',
  PROMO_CODE_TAKEN: 'PROMO_CODE_TAKEN',
  PROMO_LIMIT_BELOW_USAGE: 'PROMO_LIMIT_BELOW_USAGE',
  SETTINGS_FETCHED: 'SETTINGS_FETCHED',
  SETTING_UPDATED: 'SETTING_UPDATED',
  SETTING_RESET: 'SETTING_RESET',
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  FINANCE_OVERVIEW_FETCHED: 'FINANCE_OVERVIEW_FETCHED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_SETTLED: 'WITHDRAWAL_SETTLED',
  WITHDRAWAL_FAILED: 'WITHDRAWAL_FAILED',
  PAYOUT_DETAILS_FETCHED: 'PAYOUT_DETAILS_FETCHED',
  PAYMENTS_FETCHED: 'PAYMENTS_FETCHED',
  WALLET_ADJUSTED: 'WALLET_ADJUSTED',
  REMITTANCE_RECORDED: 'REMITTANCE_RECORDED',
  REFUNDS_FETCHED: 'REFUNDS_FETCHED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_SETTLED: 'REFUND_SETTLED',
  REFUND_FAILED: 'REFUND_FAILED',
  REFUND_NOT_FOUND: 'REFUND_NOT_FOUND',
  REFUND_NOT_SETTLEABLE: 'REFUND_NOT_SETTLEABLE',
  PAYMENT_NOT_REFUNDABLE: 'PAYMENT_NOT_REFUNDABLE',
  REFUND_EXCEEDS_PAYMENT: 'REFUND_EXCEEDS_PAYMENT',
  ADMIN_CUSTOMERS_FETCHED: 'ADMIN_CUSTOMERS_FETCHED',
  ADMIN_CUSTOMER_FETCHED: 'ADMIN_CUSTOMER_FETCHED',
  CUSTOMER_SUSPENDED: 'CUSTOMER_SUSPENDED',
  CUSTOMER_REINSTATED: 'CUSTOMER_REINSTATED',
  CUSTOMER_NOT_SUSPENDED: 'CUSTOMER_NOT_SUSPENDED',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  LIVE_DELIVERIES_FETCHED: 'LIVE_DELIVERIES_FETCHED',
  DELIVERY_TIMELINE_FETCHED: 'DELIVERY_TIMELINE_FETCHED',
  DELIVERY_REASSIGNED: 'DELIVERY_REASSIGNED',
  DELIVERY_NOT_REASSIGNABLE: 'DELIVERY_NOT_REASSIGNABLE',

  // ── Uploads ──
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_FETCHED: 'FILE_FETCHED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
} as const;

export type ResponseCode = (typeof ResponseCode)[keyof typeof ResponseCode];

/**
 * Default human message per code. A code with no entry falls back to a
 * humanised form of the code itself, so adding a code never breaks a response.
 */
export const RESPONSE_MESSAGES: Partial<Record<ResponseCode, string>> = {
  SUCCESS: 'Request completed successfully.',
  CREATED: 'Resource created successfully.',
  UPDATED: 'Resource updated successfully.',
  DELETED: 'Resource deleted successfully.',
  FETCHED: 'Resource fetched successfully.',

  VALIDATION_ERROR: 'Validation failed.',
  UNAUTHORIZED: 'Authentication is required.',
  FORBIDDEN: 'You do not have permission to perform this action.',
  NOT_FOUND: 'Resource not found.',
  CONFLICT: 'The request conflicts with the current state of the resource.',
  RATE_LIMIT_EXCEEDED: 'Too many requests. Please try again later.',
  INTERNAL_ERROR: 'An unexpected error occurred. Please try again.',
  SERVICE_UNAVAILABLE: 'The service is temporarily unavailable.',

  INVALID_CREDENTIALS: 'Phone number or password is incorrect.',
  ACCOUNT_ALREADY_EXISTS: 'An account with this phone number already exists.',
  ACCOUNT_NOT_VERIFIED: 'This account has not been verified yet.',
  ACCOUNT_SUSPENDED: 'This account has been suspended.',
  OTP_INVALID: 'The verification code is incorrect.',
  OTP_EXPIRED: 'The verification code has expired. Please request a new one.',
  OTP_MAX_ATTEMPTS_REACHED: 'Too many incorrect attempts. Please request a new code.',
  OTP_RESEND_TOO_SOON: 'Please wait before requesting another code.',
  OTP_RATE_LIMITED: 'Too many verification codes requested. Please try again later.',
  REFRESH_TOKEN_INVALID: 'The refresh token is invalid.',
  REFRESH_TOKEN_REUSED: 'This session has been revoked for security reasons. Please sign in again.',
  ACCESS_TOKEN_EXPIRED: 'Your session has expired. Please sign in again.',

  DELIVERY_ALREADY_ASSIGNED: 'This delivery has already been assigned to another driver.',
  DELIVERY_INVALID_TRANSITION: 'This action is not allowed for the current delivery status.',
  DELIVERY_NOT_CANCELLABLE: 'This delivery can no longer be cancelled.',
  DELIVERY_NO_DRIVER_FOUND: 'No driver is available nearby right now. Please try again shortly.',
  DELIVERY_NOT_REASSIGNABLE:
    'Only a delivery with an assigned driver who has not yet collected the package can be reassigned.',
  PROOF_OF_DELIVERY_REQUIRED: 'A proof-of-delivery photo is required before completing this delivery.',

  DRIVER_NOT_APPROVED: 'Your driver account has not been approved yet.',
  DRIVER_DOCUMENTS_INCOMPLETE: 'Please upload all required documents before going online.',
  DRIVER_VEHICLE_REQUIRED: 'Please register a vehicle before going online.',
  DRIVER_HAS_ACTIVE_DELIVERY: 'You already have an active delivery.',
  DRIVER_ALREADY_APPROVED: 'This driver is already approved.',
  DRIVER_NOT_SUSPENDED: 'Only a suspended driver can be reinstated.',
  CUSTOMER_NOT_SUSPENDED: 'Only a suspended customer can be reinstated.',
  DOCUMENT_NOT_FOUND: 'This document does not belong to this driver.',
  VEHICLE_TYPE_CODE_TAKEN: 'Another vehicle type already uses this code.',
  ROLE_NAME_TAKEN: 'Another role already uses this name.',
  ROLE_IS_SYSTEM: 'System roles cannot be changed.',
  ROLE_IN_USE: 'Operators still hold this role.',
  SUPER_ADMIN_REQUIRED: 'Only a super admin can do this.',
  CANNOT_MODIFY_SELF: 'You cannot change your own access.',
  LAST_SUPER_ADMIN: 'The platform must keep at least one super admin.',
  ZONE_CODE_TAKEN: 'Another zone already uses this code.',
  PAYMENT_NOT_REFUNDABLE: 'This delivery has no settled online payment to refund.',
  REFUND_EXCEEDS_PAYMENT: 'That is more than is left to refund on this payment.',
  REFUND_NOT_SETTLEABLE: 'Only a pending refund can be settled or marked failed.',
  PROMO_CODE_TAKEN: 'Another promo code already uses this code.',
  ZONE_NOT_FOUND: 'One or more zones do not exist.',

  JOB_OFFER_EXPIRED: 'This job request has expired.',
  JOB_ALREADY_RESPONDED: 'You have already responded to this job request.',

  INSUFFICIENT_BALANCE: 'Your wallet balance is not sufficient for this withdrawal.',
  WITHDRAWAL_PENDING_EXISTS: 'You already have a withdrawal request awaiting processing.',
  WITHDRAWAL_SETTINGS_REQUIRED: 'Please add your bank account details before requesting a withdrawal.',
};

/** `DELIVERY_CREATED` → `Delivery created`. No trailing punctuation. */
export function humaniseCode(code: string): string {
  const sentence = code.toLowerCase().split('_').join(' ');
  return `${sentence.charAt(0).toUpperCase()}${sentence.slice(1)}`;
}

/**
 * Message for a failure. Never says "successfully" — a humanised
 * `ADDRESS_NOT_FOUND` must read "Address not found.", not
 * "Address not found successfully."
 */
export function messageForCode(code: ResponseCode): string {
  return RESPONSE_MESSAGES[code] ?? `${humaniseCode(code)}.`;
}

/** Message for a success envelope, where "successfully" reads naturally. */
export function successMessageForCode(code: ResponseCode): string {
  return RESPONSE_MESSAGES[code] ?? `${humaniseCode(code)} successfully.`;
}
